@WebApp.Server_HostAddress = http://localhost:5036

POST {{WebApp.Server_HostAddress}}/register/
Content-Type: application/json
Accept: */*

{
    "companyName": "companyName",
    "industryId": "1",
    "firstName": "firstName",
    "lastName": "lastName",
    "userName": "username",
    "password": "pa$$w0rD",
    "email": ""
}
###
